/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a astroprocessadaptor -i astroprocess.h -l AstroComputing /skylendar/builds/ubuntu/src/astroprocess.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ASTROPROCESSADAPTOR_H
#define ASTROPROCESSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "astroprocess.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.skylendar.skyservice
 */
class SkyserviceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.skylendar.skyservice")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.skylendar.skyservice\">\n"
"    <method name=\"GetVersion\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </method>\n"
"    <method name=\"SetExtraData\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"utc\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"swepaths\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"temp\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"press\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"humid\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"nbstars\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"eit\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"sti\"/>\n"
"    </method>\n"
"    <method name=\"Date_Conversion\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"day\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"month\"/>\n"
"      <arg direction=\"in\" type=\"n\" name=\"year\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"utime\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"greg\"/>\n"
"    </method>\n"
"    <method name=\"Local2Mean\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"j\"/>\n"
"    </method>\n"
"    <method name=\"GetObliquity\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"    </method>\n"
"    <method name=\"DBusRevJul\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jd\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"greg\"/>\n"
"    </method>\n"
"    <method name=\"DBusAzalt\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jd\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"geopos\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"xin\"/>\n"
"    </method>\n"
"    <method name=\"DBusAzaltP\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jd\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"geopos\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"xin\"/>\n"
"    </method>\n"
"    <method name=\"DBusConvert\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"lon\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"lat\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"ecl\"/>\n"
"    </method>\n"
"    <method name=\"DBusGetPlaName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetMagnitude\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"SidTime\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jd\"/>\n"
"    </method>\n"
"    <method name=\"Day_of_Week\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jd\"/>\n"
"    </method>\n"
"    <method name=\"InitRestricts\">\n"
"      <arg direction=\"in\" type=\"ay\" name=\"art\"/>\n"
"    </method>\n"
"    <method name=\"SetRestrict\">\n"
"      <arg direction=\"in\" type=\"ay\" name=\"art\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"SetXPoint\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"angle\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"lat\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"dist\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"    </method>\n"
"    <method name=\"Recompute\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"dct\"/>\n"
"    </method>\n"
"    <method name=\"GetValues\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"slot\"/>\n"
"    </method>\n"
"    <method name=\"DBusGetError\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"Kill\"/>\n"
"    <method name=\"ScanAsp\">\n"
"      <arg direction=\"in\" type=\"ay\" name=\"dct\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"origjd\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"scserver\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"dual\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"mp\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"tosecond\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"ap\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"ScanDir\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"first\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"second\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"scserver\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"house\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"dirtype\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"statkey\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"dval\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"StopScan\">\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"GetRiseSet\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"latitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"longitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"altitude\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ca\"/>\n"
"    </method>\n"
"    <method name=\"ComputeGlobEclipse\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"direction\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"lunar\"/>\n"
"    </method>\n"
"    <method name=\"ComputeLocEclipse\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"latitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"longitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"altitude\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"direction\"/>\n"
"    </method>\n"
"    <method name=\"ComputeEclPos\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"    </method>\n"
"    <method name=\"LunarOccult\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"latitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"longitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"altitude\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"direction\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"local\"/>\n"
"    </method>\n"
"    <method name=\"GetEclipseValue\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"DBusGetApsides\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"flags\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"method\"/>\n"
"    </method>\n"
"    <method name=\"GetSunStep\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jd\"/>\n"
"    </method>\n"
"    <method name=\"IfParts\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"LoadParts\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"dbv\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"size\"/>\n"
"    </method>\n"
"    <method name=\"Gauquelin\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"julday\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"geolat\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"latitude\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"longitude\"/>\n"
"    </method>\n"
"    <method name=\"GetHousePos\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"slot\"/>\n"
"    </method>\n"
"    <method name=\"DBusHeliacal\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"juday\"/>\n"
"      <arg direction=\"in\" type=\"ay\" name=\"geopos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"type\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SkyserviceAdaptor(AstroComputing *parent);
    virtual ~SkyserviceAdaptor();

    inline AstroComputing *parent() const
    { return static_cast<AstroComputing *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int ComputeEclPos(double julday, int flags);
    int ComputeGlobEclipse(double julday, int flags, bool direction, bool lunar);
    int ComputeLocEclipse(double julday, int flags, double latitude, double longitude, double altitude, bool direction);
    QByteArray DBusAzalt(double jd, int flags, const QByteArray &geopos, const QByteArray &xin);
    QByteArray DBusAzaltP(double jd, int flags, const QByteArray &geopos, const QByteArray &xin);
    QByteArray DBusConvert(double lon, double lat, double ecl);
    QByteArray DBusGetApsides(double julday, int index, int flags, int method);
    QString DBusGetError();
    QString DBusGetPlaName(int i);
    QByteArray DBusHeliacal(double juday, const QByteArray &geopos, int id, int type);
    QByteArray DBusRevJul(double jd, bool greg);
    double Date_Conversion(uchar day, uchar month, short year, double utime, bool greg);
    int Day_of_Week(double jd);
    double Gauquelin(double julday, double geolat, double latitude, double longitude);
    double GetEclipseValue(int i);
    QByteArray GetHousePos(int slot);
    double GetMagnitude(int i);
    double GetObliquity(double julday);
    double GetRiseSet(double julday, int index, double latitude, double longitude, double altitude, int ca);
    double GetSunStep(double jd);
    QByteArray GetValues(int slot);
    double GetVersion();
    bool IfParts();
    void InitRestricts(const QByteArray &art);
    void Kill();
    bool LoadParts(const QByteArray &dbv, int size);
    double Local2Mean(double j);
    int LunarOccult(double julday, int i, int flags, double latitude, double longitude, double altitude, bool direction, bool local);
    bool Recompute(const QByteArray &dct);
    Q_NOREPLY void ScanAsp(const QByteArray &dct, double origjd, const QString &scserver, bool dual, bool mp, bool tosecond, bool ap);
    Q_NOREPLY void ScanDir(int first, int second, const QString &scserver, uchar house, uchar dirtype, uchar statkey, double dval, int flags);
    void SetExtraData(bool utc, const QString &swepaths, double temp, double press, uchar humid, int nbstars, const QByteArray &eit, const QByteArray &sti);
    void SetRestrict(const QByteArray &art, int i);
    void SetXPoint(double angle, double lat, double dist, int ring);
    double SidTime(double jd);
    Q_NOREPLY void StopScan();
Q_SIGNALS: // SIGNALS
};

#endif
