/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p astroprocessinterface /skylendar/builds/ubuntu/src/astroprocess.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "astroprocessinterface.h"

/*
 * Implementation of interface class OrgSkylendarSkyserviceInterface
 */

OrgSkylendarSkyserviceInterface::OrgSkylendarSkyserviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgSkylendarSkyserviceInterface::~OrgSkylendarSkyserviceInterface()
{
}


#include "astroprocessinterface.moc"
