/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a astrogetvaluesadaptor -i astrogetvalues.h -l AstroGetValues /skylendar/builds/ubuntu/src/astrogetvalues.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ASTROGETVALUESADAPTOR_H
#define ASTROGETVALUESADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "astrogetvalues.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.skylendar.vals
 */
class ValsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.skylendar.vals")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.skylendar.vals\">\n"
"    <method name=\"NbCharts\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetChartName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"LockChart\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"UnlockChart\"/>\n"
"    <method name=\"NbRings\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetRingType\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"IfObj\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj\"/>\n"
"    </method>\n"
"    <method name=\"GetVal\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"n\"/>\n"
"    </method>\n"
"    <method name=\"GetLong\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj\"/>\n"
"    </method>\n"
"    <method name=\"NbAspects\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetAspect\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"NbMPAspects\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetMPAspect\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"    <method name=\"SearchAspect\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"asp\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj2\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"start\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj3\"/>\n"
"    </method>\n"
"    <method name=\"GetMidPoint\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj2\"/>\n"
"    </method>\n"
"    <method name=\"GetEphemLine\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"day\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"month\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"year\"/>\n"
"    </method>\n"
"    <method name=\"GetPart\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"    </method>\n"
"    <method name=\"GetDecan\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"    </method>\n"
"    <method name=\"GetTerm\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"obj\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"ring\"/>\n"
"    </method>\n"
"    <method name=\"TFReq\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"s\"/>\n"
"    </method>\n"
"    <method name=\"TFNext\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"TFGetAsp\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ValsAdaptor(AstroGetValues *parent);
    virtual ~ValsAdaptor();

    inline AstroGetValues *parent() const
    { return static_cast<AstroGetValues *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetAspect(int i);
    QString GetChartName();
    QString GetDecan(const QString &obj, int ring);
    QString GetEphemLine(int day, int month, int year);
    double GetLong(int ring, const QString &obj);
    QString GetMPAspect(int i);
    double GetMidPoint(const QString &obj1, const QString &obj2);
    double GetPart(int i, int ring);
    QString GetRingType(int i);
    QString GetTerm(const QString &obj, int ring);
    double GetVal(int ring, const QString &obj, int n);
    bool IfObj(int ring, const QString &obj);
    bool LockChart(int i);
    int NbAspects();
    int NbCharts();
    int NbMPAspects();
    int NbRings();
    int SearchAspect(const QString &obj1, const QString &asp, const QString &obj2, int start, const QString &obj3);
    int TFGetAsp(int i);
    bool TFNext();
    bool TFReq(const QString &s);
    void UnlockChart();
Q_SIGNALS: // SIGNALS
};

#endif
