/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a scanclientadaptor -i scanclient.h -l ScanClient /skylendar/builds/ubuntu/src/scanclient.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "scanclientadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ScanclientAdaptor
 */

ScanclientAdaptor::ScanclientAdaptor(ScanClient *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ScanclientAdaptor::~ScanclientAdaptor()
{
    // destructor
}

void ScanclientAdaptor::EndScan()
{
    // handle method call org.skylendar.scanclient.EndScan
    parent()->EndScan();
}

void ScanclientAdaptor::GetAspect(int i, double ipos, int j, double jpos, int aspect, double date)
{
    // handle method call org.skylendar.scanclient.GetAspect
    parent()->GetAspect(i, ipos, j, jpos, aspect, date);
}

void ScanclientAdaptor::GetAspect(int i, double ipos, int j, double jpos, int aspect, double date, bool ap)
{
    // handle method call org.skylendar.scanclient.GetAspect
    parent()->GetAspect(i, ipos, j, jpos, aspect, date, ap);
}

void ScanclientAdaptor::GetDirection(int i, double ipos, int j, double jpos, int aspect, double date, bool converse)
{
    // handle method call org.skylendar.scanclient.GetDirection
    parent()->GetDirection(i, ipos, j, jpos, aspect, date, converse);
}

void ScanclientAdaptor::GetMPAspect(int i, int j, double pos, int k, double kpos, int aspect, double date)
{
    // handle method call org.skylendar.scanclient.GetMPAspect
    parent()->GetMPAspect(i, j, pos, k, kpos, aspect, date);
}

void ScanclientAdaptor::GetRetro(int i, double ipos, double date)
{
    // handle method call org.skylendar.scanclient.GetRetro
    parent()->GetRetro(i, ipos, date);
}

void ScanclientAdaptor::GetSignTrans(int i, int sign, double date)
{
    // handle method call org.skylendar.scanclient.GetSignTrans
    parent()->GetSignTrans(i, sign, date);
}

void ScanclientAdaptor::Progress(int i)
{
    // handle method call org.skylendar.scanclient.Progress
    parent()->Progress(i);
}


#include "scanclientadaptor.moc"
