/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a scanclientadaptor -i scanclient.h -l ScanClient /skylendar/builds/ubuntu/src/scanclient.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SCANCLIENTADAPTOR_H
#define SCANCLIENTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "scanclient.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.skylendar.scanclient
 */
class ScanclientAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.skylendar.scanclient")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.skylendar.scanclient\">\n"
"    <method name=\"GetAspect\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"ipos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"j\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jpos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"aspect\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"date\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"ap\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"GetAspect\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"ipos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"j\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jpos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"aspect\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"date\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"GetMPAspect\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"j\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"pos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"k\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"kpos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"aspect\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"date\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"GetRetro\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"ipos\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"date\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"GetSignTrans\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"sign\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"date\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"GetDirection\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"ipos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"j\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"jpos\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"aspect\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"date\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"converse\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"Progress\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"i\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"EndScan\">\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ScanclientAdaptor(ScanClient *parent);
    virtual ~ScanclientAdaptor();

    inline ScanClient *parent() const
    { return static_cast<ScanClient *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    Q_NOREPLY void EndScan();
    Q_NOREPLY void GetAspect(int i, double ipos, int j, double jpos, int aspect, double date);
    Q_NOREPLY void GetAspect(int i, double ipos, int j, double jpos, int aspect, double date, bool ap);
    Q_NOREPLY void GetDirection(int i, double ipos, int j, double jpos, int aspect, double date, bool converse);
    Q_NOREPLY void GetMPAspect(int i, int j, double pos, int k, double kpos, int aspect, double date);
    Q_NOREPLY void GetRetro(int i, double ipos, double date);
    Q_NOREPLY void GetSignTrans(int i, int sign, double date);
    Q_NOREPLY void Progress(int i);
Q_SIGNALS: // SIGNALS
};

#endif
