/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p scanclientinterface /skylendar/builds/ubuntu/src/scanclient.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "scanclientinterface.h"

/*
 * Implementation of interface class OrgSkylendarScanclientInterface
 */

OrgSkylendarScanclientInterface::OrgSkylendarScanclientInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgSkylendarScanclientInterface::~OrgSkylendarScanclientInterface()
{
}


#include "scanclientinterface.moc"
